### ISSUE TITLE
Color PaletteARCHIVE

### ISSUE THREAD

**Issue by tmacdonald18** [tmacdonald18/game_dev#1]
Need to create some sort of shared color palette  in order to maintain consistency between all drawings.  We should determine different levels of hue/saturation for each color of the rAiNbOw.  We should also discuss shading, and whether we want that incorporated into the sprites themselves or as a dynamic element of the game engine.

**Comment by GlitchRain** [comment]
Color palette should be limited to 4-6 basic colors.  Can include black and gray.

**Comment by GlitchRain** [comment]
idea: demo level to have dark color palette

Color - Hex Code in GIMP

Black - 000000
Dark Gray - 292929
Gray - 4d4d4d
Light Gray - 9b9b9b
Yellow (For any lamps/light sources) - ffffac
Dark Yellow - b3b279
