### ISSUE TITLE
Level DesignARCHIVE

### ISSUE THREAD

**Issue by tmacdonald18** [tmacdonald18/game_dev#8]
Need someone to generate a ".csv" file with numbers indicating each unique type of tile.  Essentially, this task involves actually designing the level, getting it approved by everyone else, and then creating the data sheet with the correct format.  See Tyler for formatting guidelines.

Designing the level includes enemy placement, traps, triggers, events, collisions, and tiles.  There's a lot to it.

Might look into creating a simple GUI which would make it easier to create these types of files.

**Comment by GlitchRain** [comment]
Things we need to exhibit in demo level:

Walk section
Run section
Sliding section
Jumping section
Fall section
Enemy section
Boss section
